import { useMemo, useState } from 'react'
import { approveReview, type FlagItem, type ReviewDetail, type SuggestionItem } from '../api'

const SOURCE_LABEL: Record<string, string> = {
  parsing: 'Document Parsing',
  literature: 'Literature Survey',
  architecture: 'Architecture Structure',
  alignment: 'Alignment',
}

interface ReviewApprovalPanelProps {
  detail: ReviewDetail
  onApproved: (updated: ReviewDetail) => void
}

export default function ReviewApprovalPanel({ detail, onApproved }: ReviewApprovalPanelProps) {
  const [flags, setFlags] = useState<FlagItem[]>(() => detail.all_flags.map((f) => ({ ...f })))
  const [suggestions, setSuggestions] = useState<SuggestionItem[]>(() => detail.suggestions.map((s) => ({ ...s })))
  const [gapSummary, setGapSummary] = useState(detail.research_gap_summary)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const grouped = useMemo(() => {
    const groups: Record<string, { index: number; flag: FlagItem }[]> = {}
    flags.forEach((flag, index) => {
      const key = flag.source || 'general'
      groups[key] = groups[key] || []
      groups[key].push({ index, flag })
    })
    return groups
  }, [flags])

  function toggleFlag(index: number) {
    setFlags((prev) => prev.map((f, i) => (i === index ? { ...f, included: !f.included } : f)))
  }

  function toggleSuggestion(index: number) {
    setSuggestions((prev) => prev.map((s, i) => (i === index ? { ...s, included: !s.included } : s)))
  }

  async function handleApprove() {
    setError(null)
    setIsSubmitting(true)
    try {
      const updated = await approveReview(detail.id, {
        all_flags: flags,
        suggestions,
        research_gap_summary: gapSummary,
      })
      onApproved(updated)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not approve this review.')
    } finally {
      setIsSubmitting(false)
    }
  }

  const includedCount = flags.filter((f) => f.included).length

  return (
    <div className="space-y-6">
      <div className="rounded-xl border border-brand-200 bg-brand-50/60 px-4 py-3.5 text-[12.5px] leading-relaxed text-brand-900">
        <strong className="font-semibold">Faculty review required.</strong> The findings below were generated by the
        AI pipeline and have not yet reached the student. Uncheck anything that shouldn't be included, edit the
        research gap summary if needed, then approve to generate the final report.
      </div>

      <div className="rounded-xl2 border border-line bg-paper-raised p-6 shadow-card sm:p-8">
        <div className="mb-5 flex items-center justify-between">
          <h3 className="text-[15px] font-semibold text-ink">Flagged Issues</h3>
          <span className="text-[12px] text-ink-faint">
            {includedCount} of {flags.length} included
          </span>
        </div>

        {flags.length === 0 ? (
          <p className="text-[13.5px] text-ink-muted">No issues were flagged.</p>
        ) : (
          <div className="space-y-6">
            {Object.entries(grouped).map(([source, items]) => (
              <div key={source}>
                <p className="mb-2.5 text-[12.5px] font-semibold uppercase tracking-wide text-ink-muted">
                  {SOURCE_LABEL[source] || source}
                </p>
                <ul className="space-y-2">
                  {items.map(({ index, flag }) => (
                    <li key={index}>
                      <label className="flex cursor-pointer items-start gap-3 rounded-lg border border-line-soft bg-line-soft/30 px-3.5 py-2.5 text-[13.5px] leading-relaxed text-ink transition-opacity has-[:checked]:opacity-100 opacity-70">
                        <input
                          type="checkbox"
                          checked={flag.included}
                          onChange={() => toggleFlag(index)}
                          className="mt-0.5 h-4 w-4 shrink-0 accent-brand-700"
                        />
                        {flag.text}
                      </label>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="rounded-xl2 border border-line bg-paper-raised p-6 shadow-card sm:p-8">
        <h3 className="mb-3 text-[15px] font-semibold text-ink">Research Gap Summary</h3>
        <textarea
          value={gapSummary}
          onChange={(e) => setGapSummary(e.target.value)}
          rows={4}
          className="w-full rounded-lg border border-line bg-paper px-3.5 py-2.5 text-[13.5px] leading-relaxed text-ink outline-none transition-colors focus:border-brand-400"
          placeholder="No research gap was identified."
        />
      </div>

      <div className="rounded-xl2 border border-brand-200 bg-brand-50/50 p-6 shadow-card sm:p-8">
        <h3 className="mb-4 text-[15px] font-semibold text-ink">Improvement Suggestions</h3>
        {suggestions.length === 0 ? (
          <p className="text-[13.5px] text-ink-muted">No suggestions to show.</p>
        ) : (
          <ol className="space-y-2.5">
            {suggestions.map((s, index) => (
              <li key={index}>
                <label className="flex cursor-pointer items-start gap-3 rounded-lg border border-brand-200 bg-paper-raised px-4 py-2.5 text-[13.5px] leading-relaxed text-ink opacity-70 transition-opacity has-[:checked]:opacity-100">
                  <input
                    type="checkbox"
                    checked={s.included}
                    onChange={() => toggleSuggestion(index)}
                    className="mt-0.5 h-4 w-4 shrink-0 accent-brand-700"
                  />
                  {s.text}
                </label>
              </li>
            ))}
          </ol>
        )}
      </div>

      {error && <p className="rounded-lg bg-band-lowBg px-4 py-3 text-[13px] text-band-low">{error}</p>}

      <button
        onClick={handleApprove}
        disabled={isSubmitting}
        className="w-full rounded-xl bg-brand-700 py-3.5 text-[14.5px] font-semibold text-white shadow-card transition-all duration-200 hover:bg-brand-800 disabled:opacity-60"
      >
        {isSubmitting ? 'Generating final report…' : 'Approve & Generate Final Report'}
      </button>
    </div>
  )
}
